### ISSUE TITLE
"server_name" directive in /etc/nginx/conf.d/vhost.conf:3

### ISSUE THREAD

**Issue by Paulmicha** [Wodby/nginx-php-5.6-alpine#2]
I did a test running the following `docker-compose.yml` (the `environment` vars are wild guesses based on the `Wodby/docker4drupal` repo) :

```
version: "2"

services:
  nginx:
    image: wodby/nginx-php-5.6-alpine
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: php
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost:80
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
```

It fails when running :
```
docker-compose up -d
```

→ in `docker-compose logs nginx` :
```
nginx_1  | nginx: [emerg] invalid number of arguments in "server_name" directive in /etc/nginx/conf.d/vhost.conf:3
nginx_1  | ./run: exec: line 3: /opt/wodby/tools/bin/confd: not found
```

**What am I missing ?**

Tested in Debian 8.6 (jessie) with Docker version 1.12.3, build 6b644ec and docker-compose version 1.9.0-rc2, build a2da43b on 2016/11/01.
